## Problem Set 2
Emma (Sunwoo) Cho

1. Read through the Standard Library Chapter (located at /CompEcon_Fall25/Python/ACME_StandardLibary.pdf).
Complete Problems 1-3.

Problem 1

In [17]:
# problem 1: Write a function that accepts a list L and returns the
# min, max, avg of the entries of L (in that order)
# Q) Can you implement this function in a single line?

import numpy as np
L = list(map(float, input("Enter the list (e.g. 1,2,3): ").split(',')))
basicStats = lambda x: (min(x), max(x), round(float(np.mean(x)),3))
print("min, max, mean =", basicStats(L))

Enter the list (e.g. 1,2,3): 1,2,3
min, max, mean = (1.0, 3.0, 2.0)


Problem 2

In [10]:
# (1) int: immutable
int1 = 1      # create new int
int2 = int1   # assign a new name
int2 += 1     # change the new int
int1 == int2  # compare two

# False: immutable

# from below, I omit the explanations(# for each line), just followed the instruction as PS2

False

In [12]:
# (2) string: immutable
str1 = "one"
str2 = str1
str2 += " two"
str1 == str2

# False: immutable

False

In [13]:
# (3) list: mutable
list1 = [1, 2, 3, 4, 5]
list2 = list1
list2.append(6)
list1 == list2

# True: mutable

True

In [14]:
# (4) tuple: immutable
t1 = (1, 2, 3, 4, 5)
t2 = t1
t2 += (6,)
t1 == t2

# False: immutable

False

In [15]:
# (5) set: mutable
set1 = {1, 2, 3, 4, 5}
set2 = set1
set2.add(6)
set1 == set2

True

In [16]:
# Immutable types: int, str, tuple
# Mutable types: list, set, dict

Problem 3

In [6]:
%%writefile /content/calculator.py
from math import sqrt

def add(a, b):
    return a + b

def multiply(a, b):
    return a * b

Writing /content/calculator.py


In [7]:
# test
import calculator
calculator.add(2, 3), calculator.multiply(4, 5)


(5, 20)

In [8]:
# solution
import calculator

def hypotenuse(a, b):
    # c = sqrt(a^2 + b^2)
    return calculator.sqrt(
        calculator.add(calculator.multiply(a, a), calculator.multiply(b, b)))

In [9]:
if __name__ == "__main__":
    print(hypotenuse(3, 4))  # 5.0

5.0


2. Read through the Introduction to Numpy chapter (located at /CompEcon_Fall25/Python/ACME_NumpyIntro.pdf). Complete Problems 1, 2, 5.

In [19]:
# problem 1
import numpy as np

def mat_multi():
    A = np.array([[3, -1,  4],
                  [1,  5, -9]])
    B = np.array([[ 2,  6, -5,  3],
                  [ 5, -8,  9,  7],
                  [ 9, -3, -2, -3]])
    return A @ B
    # np.dot(A, B) also possible as in the question stated

AB = mat_multi()
print(AB)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [20]:
# problem 2
import numpy as np

def cayley_hamilton_cal():
    A = np.array([[ 3, 1, 4],
                  [ 1, 5, 9],
                  [-5, 3, 1]])
    A2 = A @ A
    A3 = A2 @ A
    return -A3 + 9*A2 - 15*A

result = cayley_hamilton_cal()
print(result)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
# problem 5

import numpy as np

A = np.array([[0, 2, 4],
              [1, 3, 5]], dtype=int) # 2×3
B = np.array([[3, 0, 0],
              [3, 3, 0],
              [3, 3, 3]], dtype=int) # 3×3
C = np.diag([-2, -2, -2]) # 3×3

block_mat = np.block([
    [np.zeros((3,3), dtype=int),  A.T, np.eye(3, dtype=int)],
    [A, np.zeros((2,2), dtype=int), np.zeros((2,3), dtype=int)],
    [B, np.zeros((3,2), dtype=int), C]])

print(block_mat.shape)
print(block_mat)


(8, 8)
[[ 0  0  0  0  1  1  0  0]
 [ 0  0  0  2  3  0  1  0]
 [ 0  0  0  4  5  0  0  1]
 [ 0  2  4  0  0  0  0  0]
 [ 1  3  5  0  0  0  0  0]
 [ 3  0  0  0  0 -2  0  0]
 [ 3  3  0  0  0  0 -2  0]
 [ 3  3  3  0  0  0  0 -2]]


3. Read through the Object Oriented Programming chapter (located at
/CompEcon_Fall25/Python/ACME_ObjectOriented.pdf). Complete Problems 1 and 2.

In [25]:
# problem 1
class Backpack:
    def __init__(self, name: str, color: str, max_size: int=5):
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []

    def put(self, item):
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        self.contents.append(item)

    def dump(self):
        self.contents = []


# test function
def test_backpack():
    testpack = Backpack("Barry", "black")  # Instantiate the object.

    if testpack.name != "Barry": # Test an attribute.
        print("Backpack.name assigned incorrectly")

    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item) # Test a method.

    print("Contents:", testpack.contents)

    while len(testpack.contents) < testpack.max_size:
          testpack.put("chocolate")

    testpack.put("milk")

    # test dump()
    testpack.dump()
    print("If we perform dump - contents:", testpack.contents)

if __name__ == "__main__":
    test_backpack()


Contents: ['pencil', 'pen', 'paper', 'computer']
No Room!
If we perform dump - contents: []


In [26]:
# problem 2
# assume as Backpack defined as problem 1 as in the above code

class Jetpack(Backpack):
    def __init__(self, name: str, color: str, max_size: int=2, fuel: int=10):
        super().__init__(name, color, max_size)
        self.fuel = fuel

    def fly(self, burn: int):
        if burn > self.fuel:
            print("Not enough fuel!")
            return
        self.fuel -= burn

    def dump(self):
        super().dump()
        self.fuel = 0

# test
def test_jetpack():
    pack = Jetpack("cookie", "cream")  # max_size=2, fuel=10 (default setting)

    # capacity check from Backpack (Q1):
    pack.put("banana")
    pack.put("juice")
    pack.put("coke")  # extra--> so "No Room!""

    # fly(): normal, burn more fuel than remains
    print("before:", pack.fuel)  # 10
    pack.fly(3)
    print("fuel after burn:", pack.fuel)  # 7
    pack.fly(20)
    print("fuel after burn (burn more fuel than remains):", pack.fuel)  # still 7

    # test dump(): clearing both contents and fuel
    pack.dump()
    print("After dump -> contents:", pack.contents, "fuel:", pack.fuel)

if __name__ == "__main__":
    test_jetpack()

No Room!
before: 10
fuel after burn: 7
Not enough fuel!
fuel after burn (burn more fuel than remains): 7
After dump -> contents: [] fuel: 0
